# Generated by Django 4.0.5 on 2023-08-20 09:01

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nick_name",
                    models.CharField(
                        help_text="사용자가 등록한 닉네임, 별칭입니다.",
                        max_length=20,
                        verbose_name="닉네임",
                    ),
                ),
                (
                    "profile_img",
                    models.URLField(
                        default="https://picsum.photos/160",
                        help_text="사용자가 등록한 프로필 사진입니다.",
                        verbose_name="프로필사진",
                    ),
                ),
                (
                    "profile_desc",
                    models.TextField(
                        blank=True,
                        help_text="사용자가 등록한 프로필 설명입니다.",
                        null=True,
                        verbose_name="프로필",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="사용자 이름")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="사용자가 등록한 전화번호입니다.",
                        max_length=128,
                        region="KR",
                        unique=True,
                        verbose_name="사용자 전화번호",
                    ),
                ),
                (
                    "inflow",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="사용자 유입경로"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user",
                        to="user.profile",
                    ),
                ),
            ],
        ),
    ]
