# Generated by Django 4.0.5 on 2023-08-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=20, verbose_name="사용자 이름"),
        ),
    ]
