# Generated by Django 4.0.5 on 2023-08-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="inflow",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="사용자 유입경로"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=10, verbose_name="사용자 이름"),
        ),
    ]
