# prometheus.yml
global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['dda-prometheus:9090']

  - job_name: flower
    static_configs:
      - targets: ['dda-flower:5555']
