version: '3'
services:

  # ==========================================================================
  # Django Main Image - image making first
  # ==========================================================================

  daa-django: &dda-django
    build:
      context: .
      dockerfile: ./Dockerfile
    image: dda-django
    hostname: daa-django
    container_name: daa-django
    volumes:
      - ../django_all_about:/app:z
    env_file:
      - ./env
    ports:
      - "8000:8000"      
    command: /scripts/start-django.sh

  # ==========================================================================
  # Application (as S/W, as L7) WebServer - Nignx
  # ==========================================================================

  daa-nginx:
    image: nginx
    hostname: daa-nginx
    container_name: daa-nginx
    volumes:
      - ../nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/conf.d:/etc/nginx/conf.d
      - ../django_all_about/static:/etc/nginx/static
      - ../django_all_about/media:/etc/nginx/media
      - ../nginx/logs:/var/log/nginx
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    networks:
      - django-all-about-app

  # ==========================================================================
  # Sub Database nosql - mongodb
  # ==========================================================================

  daa-mongodb:
    image: mongo
    hostname: daa-mongodb
    container_name: daa-mongodb
    ports:
      - "29019:29019"
    volumes:
      - ../mongodb/data:/data/db
      - ../mongodb/cnf:/etc/mongo
      - ../mongodb/logs:/var/log/mongodb
    entrypoint: ["mongod", "-f", "/etc/mongo/mongod.conf"]
    environment:
      TZ: Asia/Seoul
    networks:
      - django-all-about-app

  # ==========================================================================
  # Main Database - postgresql
  # ==========================================================================

  daa-postgres:
    image: postgres:latest
    hostname: daa-postgres
    container_name: daa-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "nuung"
      POSTGRES_PASSWORD: "daa123!"
      POSTGRES_DB: daa-postgres-db
    volumes:
      - ../postgresql/data/:/var/lib/postgresql/data
    networks:
      - django-all-about-app

  # ==========================================================================
  # Main in-memory DB by cache and message queue
  # ==========================================================================

  daa-redis:
    image: redis:alpine
    hostname: daa-redis
    container_name: daa-redis    
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    volumes:
      - ../redis/data:/data
      - ../redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --port 6379
    networks:
      - django-all-about-app

  # ==========================================================================
  # Celery, async worker - celery & celery beat celery monitor flower
  # ==========================================================================
  
  dda-celeryworker:
    <<: *dda-django
    container_name: dda-celeryworker
    depends_on:
      - daa-redis
      - daa-postgres
    env_file:
      - ./env
    ports: []
    command: /scripts/start-celeryworker.sh

  dda-celerybeat:
    <<: *dda-django
    container_name: dda-celerybeat
    depends_on:
      - daa-redis
      - daa-postgres
    env_file:
      - ./env
    ports: []
    command: /scripts/start-celerybeat.sh

  dda-flower:
    <<: *dda-django
    container_name: dda-celeryflower
    ports:
      - "5555:5555"
    depends_on:
      - dda-celeryworker
    command: /scripts/start-flower.sh

networks:
  django-all-about-app:
    driver: bridge
