# Generated by Django 4.0.5 on 2023-02-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0003_rename_chart_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[
                    ("DE", "Default value"),
                    ("DN", "End of purchase value"),
                    ("CN", "Cancel or delete value"),
                ],
                default="DE",
                max_length=2,
            ),
        ),
    ]
