# Generated by Django 4.0.5 on 2023-03-07 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0004_cart_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="uesr",
            new_name="user",
        ),
    ]
