# Generated by Django 4.0.5 on 2023-03-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0005_rename_uesr_cart_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=100)),
                ("body", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
