# Generated by Django 4.0.5 on 2023-03-31 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0006_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("DE", "Default"), ("PU", "Public"), ("PR", "Private")],
                default="DE",
                max_length=2,
            ),
        ),
    ]
