# Generated by Django 4.0.5 on 2023-08-20 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankInfo",
            fields=[
                (
                    "bank_code",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                (
                    "remark",
                    models.TextField(
                        help_text="어떤 은행의 코드값인지 저장합니다.", verbose_name="은행"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tran_date",
                    models.DateTimeField(
                        help_text="사용자가 거래를 발생한 시간입니다.", verbose_name="거래발생시간"
                    ),
                ),
                (
                    "pay_type",
                    models.CharField(
                        choices=[
                            ("CA", "현금결제"),
                            ("VA", "벤, 카드결제"),
                            ("PG", "PG 결제"),
                            ("OT", "그 외"),
                        ],
                        default="VA",
                        max_length=2,
                    ),
                ),
                (
                    "pay_platform",
                    models.CharField(
                        help_text="사용자가 거래를 발생시킨 플랫폼입니다. 실제 결제 모듈 플랫폼 또는 회사 정보를 저장합니다.",
                        max_length=10,
                        verbose_name="거래플랫폼",
                    ),
                ),
                ("amount_total", models.DecimalField(decimal_places=0, max_digits=12)),
                ("amount_fee", models.DecimalField(decimal_places=0, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=0, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction",
                        to="user.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account",
                    models.CharField(
                        help_text="사용자가 등록한 계좌 번호를 저장합니다.",
                        max_length=16,
                        verbose_name="계좌번호",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_info",
                        to="transactions.bankinfo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_info",
                        to="user.user",
                    ),
                ),
            ],
        ),
    ]
