# Generated by Django 4.0.5 on 2023-08-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["tran_date"], name="transaction_tran_da_1b356d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["pay_type", "pay_platform"],
                name="transaction_pay_typ_c3a0d3_idx",
            ),
        ),
    ]
